# Generated by Django 3.0.2 on 2021-07-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mat_no', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved')], default=1, max_length=7)),
                ('topic_1', models.TextField(max_length=300, unique=True)),
                ('topic_2', models.TextField(max_length=300, unique=True)),
                ('topic_3', models.TextField(max_length=300, unique=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('upd_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'mat_no'],
            },
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_topic', models.CharField(choices=[('1', 'topic  1'), ('2', 'topic 2'), ('3', 'topic 3')], default=None, max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Project')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project'],
            },
        ),
    ]
