# Generated by Django 3.0.2 on 2021-07-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Assign')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Project')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
    ]
